name: 'Keystone action'
description: 'Action to use keystone github CI integration.'
inputs:
  token:
    description: 'Github accest token'
    required: false
    default: '${{ github.token }}'
  files:
    description: 'Line feed separated list of files secrets'
    required: true
runs:
  using: 'node12'
  main: 'index.js'

